version: "3.4"

services:

  app:
    image: na1al/ads:latest
    container_name: app
    hostname: app

  proxy:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: proxy
    ports:
      - 8080:8080

  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    container_name: db
    hostname: db
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}



 
