FROM na1al/ads:latest AS app

FROM nginx:1.15.8-alpine AS proxy

COPY --from=app /var/www/app/ /var/www/app/
COPY www.conf /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/nginx.conf
#COPY www /var/www/app/
#WORKDIR /var/www/app/

RUN addgroup -g 1000 -S www
RUN adduser -u 1000 -S -G www www

RUN touch /var/run/nginx.pid \
 && chown -Rf www:www \
    /var/run/nginx.pid \
    /var/cache/nginx \
    /var/log/nginx

USER www