<?php

namespace app\validators;

use yii\validators\NumberValidator;

/**
 * Class ArrayValidator
 * @package app\validators
 */
class ArrayValidator extends \yii\validators\EachValidator
{
    public int $max;

    /**
     * @param \yii\base\Model $model
     * @param string $attribute
     * @return bool|void
     */
    public function validateAttribute($model, $attribute)
    {
        if ($this->max && count($model->$attribute) > $this->max) {
            return $model->addError($attribute, \Yii::t('yii', '{attribute} must be no greater than {max} elements.', [
                'attribute' => $attribute,
                'max' => $this->max
            ]));
        }
        return parent::validateAttribute($model, $attribute); // TODO: Change the autogenerated stub
    }

}